In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
from scipy.io import mmread
sys.path.append(os.path.abspath(os.path.join('..', 'utils')))
import geo_utils
from geo_utils import read_prefixes_from_metadata_txt

root_path = '/var/datasets/single_papers/2023_feargal/GSE199750'

In [ ]:
metadata_df = read_prefixes_from_metadata_txt(f'{root_path}/GSE199750_series_matrix.txt')
print(metadata_df.shape)
metadata_df.head()

In [15]:
input_dir = f'{root_path}/GSE199750_RAW'
count_matrix = pd.DataFrame()


for file in os.listdir(input_dir):
    if file.endswith(".featureCounts.txt"):
        file_path = os.path.join(input_dir, file)
        data = pd.read_csv(file_path, comment='#', sep='\t')
        gene_counts = data[['Geneid', data.columns[-1]]]  # Last column is the count column
        sample_name = next(part for part in file.split('_') if part.startswith("GSM"))
        gene_counts.columns = ['Geneid', sample_name]
        if count_matrix.empty:
            count_matrix = gene_counts
        else:
            count_matrix = pd.merge(count_matrix, gene_counts, on='Geneid', how='outer')
count_matrix_T = count_matrix.T

In [16]:
count_matrix_T.columns = count_matrix_T.iloc[0]
count_matrix_T = count_matrix_T[1:]
#count_matrix_T.reset_index(drop=True, inplace=True)
print(count_matrix_T.shape)
count_matrix_T.head()

(260, 60671)

Geneid,ENSG00000223972,ENSG00000227232,ENSG00000278267,ENSG00000243485,ENSG00000284332,ENSG00000237613,ENSG00000268020,ENSG00000240361,ENSG00000186092,ENSG00000238009,...,ENSG00000273532,ENSG00000276351,ENSG00000275661,ENSG00000277856,ENSG00000275063,ENSG00000271254,ENSG00000275405,ENSG00000275987,ENSG00000277475,ENSG00000268674
GSM5983813,86,49,8,0,0,0,0,0,0,27,...,0,0,0,0,9,80,33,0,0,0
GSM5983814,113,32,3,0,0,1,0,0,0,18,...,0,0,0,1,11,35,31,0,0,0
GSM5983815,101,87,11,2,0,1,0,0,0,21,...,0,0,0,0,38,54,31,0,0,0
GSM5983816,71,73,2,0,0,0,0,0,0,19,...,0,0,0,2,6,159,38,0,0,0
GSM5983817,48,70,4,1,0,1,0,0,0,22,...,0,0,0,0,10,125,54,0,0,0

In [11]:
# As I only want the pre vaccine expression counts: 

metadata_v0_df = metadata_df[metadata_df['title'].str.contains('V0')]
print(metadata_v0_df.shape)
metadata_v0_df.tail()

(85, 46)

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,characteristics_ch1,...,contact_zip/postal_code,contact_country,data_row_count,instrument_model,library_selection,library_source,library_strategy,relation,relation.2,supplementary_file_1
254,COVIRS_26_22-00659_V0,GSM6395439,Public on Jan 12 2023,Jul 26 2022,Jan 12 2023,SRA,1,Peripheral blood,Homo sapiens,subject_id: COVIRS_26,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6395...
255,COVIRS_27_22-00660_V0,GSM6395440,Public on Jan 12 2023,Jul 26 2022,Jan 12 2023,SRA,1,Peripheral blood,Homo sapiens,subject_id: COVIRS_27,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6395...
256,COVIRS_57_22-00662_V0,GSM6395441,Public on Jan 12 2023,Jul 26 2022,Jan 12 2023,SRA,1,Peripheral blood,Homo sapiens,subject_id: COVIRS_57,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6395...
258,COVIRS_95_22-00667_V0,GSM6395443,Public on Jan 12 2023,Jul 26 2022,Jan 12 2023,SRA,1,Peripheral blood,Homo sapiens,subject_id: COVIRS_95,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6395...
259,COVIRS_78_22-00668_V0,GSM6395444,Public on Jan 12 2023,Jul 26 2022,Jan 12 2023,SRA,1,Peripheral blood,Homo sapiens,subject_id: COVIRS_78,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM6395...

In [19]:
combi_df = count_matrix_T.merge(metadata_v0_df, right_on='geo_accession', how='inner', left_index=True)
print(combi_df.shape)
combi_df.head()

(85, 60717)

,ENSG00000223972,ENSG00000227232,ENSG00000278267,ENSG00000243485,ENSG00000284332,ENSG00000237613,ENSG00000268020,ENSG00000240361,ENSG00000186092,ENSG00000238009,...,contact_zip/postal_code,contact_country,data_row_count,instrument_model,library_selection,library_source,library_strategy,relation,relation.2,supplementary_file_1
0,86,49,8,0,0,0,0,0,0,27,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5983...
1,113,32,3,0,0,1,0,0,0,18,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5983...
4,48,70,4,1,0,1,0,0,0,22,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5983...
5,13,43,6,1,0,0,0,0,0,36,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5983...
8,39,86,5,0,0,2,0,0,0,24,...,5021,Australia,0,DNBSEQ-G400,cDNA,transcriptomic,RNA-Seq,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5983...

In [20]:
combi_df.to_csv('/work/transcriptomics_norm_model/2023_feargal/2023_feargal_combi_df.csv')